/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MC.c
**     Project     : motor_test
**     Processor   : MC9S12ZVHL32CLL
**     Component   : Init_MC
**     Version     : Component 01.038, Driver 01.03, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2024-07-15, 13:32, # CodeGen: 1
**     Abstract    :
**          This file implements the Motor Controller (MC) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : MC
**          Device                                         : MC
**          Settings                                       : 
**            Recirculation mode                           : High side transistors
**            Fast mode                                    : no
**            Dither Feature Enable                        : no
**            Clock settings                               : 
**              Prescaler                                  : 1
**              Period counter                             : 1000
**              Period time                                : 31.25 us
**          Motors                                         : 1
**          Stop in wait mode                              : no
**          Interrupts                                     : 
**            Interrupt                                    : Vmctimovf
**            MC Interrupt overflow enable                 : Disabled
**            Priority interrupt                           : 1
**            ISR name                                     : 
**          Initialization                                 : 
**            Call Init method                             : yes
**     Contents    :
**         Init - void MC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file MC.c
** @version 01.03
** @brief
**          This file implements the Motor Controller (MC) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
*/         
/*!
**  @addtogroup MC_module MC module documentation
**  @{
*/         

/* MODULE MC. */

#include "MC.h"

/*
** ===================================================================
**     Method      :  MC_Init (component Init_MC)
**     Description :
**         This method initializes registers of the MC module according
**         to this Peripheral Initialization Component settings. Call this
**         method in the user code to initialize the module. By default,
**         the method is called by PE automatically; see "Call Init
**         method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void MC_Init(void)
{
  /* MCPER: P7=0,P6=0,P5=0,P4=0,P3=0,P2=0,P1=0,P0=0 */
  setReg8(MCPER, 0x00U);               /* Disable MC module */ 
  /* MCCTL0: ??=0,MCPRE1=0,MCPRE0=0,MCSWAI=0,FAST=0,DITH=0,??=0,MCTOIF=1 */
  setReg8(MCCTL0, 0x01U);               
  /* MCCTL1: RECIRC=0,??=0,??=0,??=0,??=0,??=0,??=0,MCTOIE=0 */
  setReg8(MCCTL1, 0x00U);               
  /* MCCC0: MCOM1=0,MCOM0=0,MCAM1=0,MCAM0=1,??=0,??=0,CD1=0,CD0=0 */
  setReg8(MCCC0, 0x10U);                
  /* MCDC0: S=0,??=0,??=0,??=0,??=0,D10=0,D9=0,D8=0,D7=0,D6=0,D5=0,D4=0,D3=0,D2=0,D1=0,D0=0 */
  setReg16(MCDC0, 0x00U);               
  /* MCCC1: MCOM1=0,MCOM0=0,MCAM1=0,MCAM0=1,??=0,??=0,CD1=0,CD0=0 */
  setReg8(MCCC1, 0x10U);                
  /* MCDC1: S=0,??=0,??=0,??=0,??=0,D10=0,D9=0,D8=0,D7=0,D6=0,D5=0,D4=0,D3=0,D2=0,D1=0,D0=0 */
  setReg16(MCDC1, 0x00U);               
  /* MCPER: ??=0,??=0,??=0,??=0,??=0,P10=0,P9=1,P8=1,P7=1,P6=1,P5=1,P4=0,P3=1,P2=0,P1=0,P0=0 */
  setReg16(MCPER, 0x03E8U);            /* Set period and enable the MC module */ 
}

/* END MC. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
