/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Vectors.c
**     Project     : motor_test
**     Processor   : MC9S12ZVHL32CLL
**     Version     : Component 01.066, Driver 02.08, CPU db: 3.00.000
**     Compiler    : CodeWarrior HCS12Z C Compiler
**     Date/Time   : 2024-07-15, 14:27, # CodeGen: 15
**     Abstract    :
**         This component "MC9S12ZVHL64_100" implements properties, methods,
**         and events of the CPU.
**     Settings    :
**
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Vectors.c                                                  
** @version 02.08
** @brief
**         This component "MC9S12ZVHL64_100" implements properties, methods,
**         and events of the CPU.
*/         
/*!
**  @addtogroup Vectors_module Vectors module documentation
**  @{
*/         
#include "Cpu.h"
#include "MC.h"

/* ISR prototype */
typedef void (*const tIsrFunc)(void);
/* Pack 3 byte pointers as 4 byte Interrupt Vector Table entries */
typedef struct
{
  byte padding;
  tIsrFunc address;
} InterruptTableEntry;
#define _VECTOR(v) {0xFFU, &v}
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
const InterruptTableEntry _InterruptVectorTable[123] @0x00FF8010U = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* ISR name                               No.  Address  Pri Name                 Description */
  _VECTOR(Cpu_Interrupt),               /* 0x04  0x00FF8010   1   ivVReserved123       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x05  0x00FF8014   1   ivVReserved122       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x06  0x00FF8018   1   ivVReserved121       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x07  0x00FF801C   1   ivVReserved120       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x08  0x00FF8020   1   ivVReserved119       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x09  0x00FF8024   1   ivVReserved118       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0A  0x00FF8028   1   ivVReserved117       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0B  0x00FF802C   1   ivVReserved116       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0C  0x00FF8030   1   ivVReserved115       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0D  0x00FF8034   1   ivVReserved114       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0E  0x00FF8038   1   ivVReserved113       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x0F  0x00FF803C   1   ivVReserved112       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x10  0x00FF8040   1   ivVReserved111       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x11  0x00FF8044   1   ivVReserved110       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x12  0x00FF8048   1   ivVReserved109       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x13  0x00FF804C   1   ivVReserved108       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x14  0x00FF8050   1   ivVReserved107       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x15  0x00FF8054   1   ivVReserved106       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x16  0x00FF8058   1   ivVReserved105       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x17  0x00FF805C   1   ivVReserved104       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x18  0x00FF8060   1   ivVssg0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x19  0x00FF8064   1   ivVrtc               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1A  0x00FF8068   1   ivVReserved101       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1B  0x00FF806C   1   ivVReserved100       unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1C  0x00FF8070   1   ivVssd1              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1D  0x00FF8074   1   ivVssd0              unused by PE */
  _VECTOR(MC_ISR),                      /* 0x1E  0x00FF8078   1   ivVmctimovf          used by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x1F  0x00FF807C   1   ivVReserved96        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x20  0x00FF8080   1   ivVReserved95        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x21  0x00FF8084   1   ivVtim1paie          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x22  0x00FF8088   1   ivVtim1paaovf        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x23  0x00FF808C   1   ivVtim1ovf           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x24  0x00FF8090   1   ivVtim1ch7           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x25  0x00FF8094   1   ivVtim1ch6           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x26  0x00FF8098   1   ivVtim1ch5           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x27  0x00FF809C   1   ivVtim1ch4           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x28  0x00FF80A0   1   ivVtim1ch3           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x29  0x00FF80A4   1   ivVtim1ch2           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2A  0x00FF80A8   1   ivVtim1ch1           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2B  0x00FF80AC   1   ivVtim1ch0           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2C  0x00FF80B0   1   ivVReserved83        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2D  0x00FF80B4   1   ivViic0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2E  0x00FF80B8   1   ivVReserved81        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x2F  0x00FF80BC   1   ivVReserved80        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x30  0x00FF80C0   1   ivVReserved79        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x31  0x00FF80C4   1   ivVReserved78        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x32  0x00FF80C8   1   ivVReserved77        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x33  0x00FF80CC   1   ivVReserved76        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x34  0x00FF80D0   1   ivVReserved75        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x35  0x00FF80D4   1   ivVReserved74        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x36  0x00FF80D8   1   ivVReserved73        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x37  0x00FF80DC   1   ivVReserved72        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x38  0x00FF80E0   1   ivVReserved71        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x39  0x00FF80E4   1   ivVReserved70        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3A  0x00FF80E8   1   ivVReserved69        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3B  0x00FF80EC   1   ivVReserved68        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3C  0x00FF80F0   1   ivVReserved67        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3D  0x00FF80F4   1   ivVportad            unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3E  0x00FF80F8   1   ivVReserved65        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x3F  0x00FF80FC   1   ivVhti               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x40  0x00FF8100   1   ivVapi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x41  0x00FF8104   1   ivVlvi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x42  0x00FF8108   1   ivVReserved61        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x43  0x00FF810C   1   ivVReserved60        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x44  0x00FF8110   1   ivVReserved59        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x45  0x00FF8114   1   ivVReserved58        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x46  0x00FF8118   1   ivVReserved57        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x47  0x00FF811C   1   ivVReserved56        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x48  0x00FF8120   1   ivVReserved55        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x49  0x00FF8124   1   ivVports             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4A  0x00FF8128   1   ivVReserved53        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4B  0x00FF812C   1   ivVportt             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4C  0x00FF8130   1   ivVReserved51        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4D  0x00FF8134   1   ivVReserved50        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4E  0x00FF8138   1   ivVReserved49        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x4F  0x00FF813C   1   ivVReserved48        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x50  0x00FF8140   1   ivVbats              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x51  0x00FF8144   1   ivVlinphy0           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x52  0x00FF8148   1   ivVReserved45        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x53  0x00FF814C   1   ivVReserved44        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x54  0x00FF8150   1   ivVcan0tx            unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x55  0x00FF8154   1   ivVcan0rx            unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x56  0x00FF8158   1   ivVcan0err           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x57  0x00FF815C   1   ivVcan0wkup          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x58  0x00FF8160   1   ivVflash             unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x59  0x00FF8164   1   ivVflasherr          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5A  0x00FF8168   1   ivVReserved37        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5B  0x00FF816C   1   ivVReserved36        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5C  0x00FF8170   1   ivVRAM_err           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5D  0x00FF8174   1   ivVReserved34        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5E  0x00FF8178   1   ivVReserved33        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x5F  0x00FF817C   1   ivVcpmuplllck        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x60  0x00FF8180   1   ivVcpmuosc           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x61  0x00FF8184   1   ivVadc0conv_compl    unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x62  0x00FF8188   1   ivVadc0conv_seq_abrt unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x63  0x00FF818C   1   ivVadc0err           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x64  0x00FF8190   1   ivVReserved27        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x65  0x00FF8194   1   ivVReserved26        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x66  0x00FF8198   1   ivVsci1              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x67  0x00FF819C   1   ivVsci0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x68  0x00FF81A0   1   ivVspi0              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x69  0x00FF81A4   1   ivVtim0paie          unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6A  0x00FF81A8   1   ivVtim0paaovf        unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6B  0x00FF81AC   1   ivVtim0ovf           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6C  0x00FF81B0   1   ivVtim0ch7           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6D  0x00FF81B4   1   ivVtim0ch6           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6E  0x00FF81B8   1   ivVtim0ch5           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x6F  0x00FF81BC   1   ivVtim0ch4           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x70  0x00FF81C0   1   ivVtim0ch3           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x71  0x00FF81C4   1   ivVtim0ch2           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x72  0x00FF81C8   1   ivVtim0ch1           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x73  0x00FF81CC   1   ivVtim0ch0           unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x74  0x00FF81D0   1   ivVrti               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x75  0x00FF81D4   1   ivVirq               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x76  0x00FF81D8   -   ivVxirq              unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x77  0x00FF81DC   -   ivVsi                unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x78  0x00FF81E0   1   ivVReserved7         unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x79  0x00FF81E4   1   ivVReserved6         unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7A  0x00FF81E8   -   ivVme                unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7B  0x00FF81EC   -   ivVsys               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7C  0x00FF81F0   -   ivVswi               unused by PE */
  _VECTOR(Cpu_Interrupt),               /* 0x7D  0x00FF81F4   -   ivVtrap              unused by PE */
  _VECTOR(Cpu_Interrupt)                /* 0x7E  0x00FF81F8   -   ivVspare             unused by PE */
};

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
const InterruptTableEntry _ResetVectorTable[1] @0x00FFE7FCU = { /* Reset vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
  /* Reset handler name                    Address Name                  Description */
  _VECTOR(_EntryPoint)                  /* 0x00FFE7FC  ivVreset              used by PE */
};
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS12Z series of microcontrollers.
**
** ###################################################################
*/
